[package]
description = """
This library includes extend features or experimental features that are useful for asynchronous programming.
"""
documentation = "https://docs.rs/rasi-ext"
edition.workspace = true
license = "MIT"
name = "rasi-ext"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rasi = { workspace = true }
dashmap = { workspace = true }
cooked-waker = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
rasi-default = { workspace = true }
futures-test = { workspace = true }

[features]
default = ["event_map"]

event_map = []
