[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/RASI.git"
version = "0.1.6"

[workspace.dependencies]
log = { version = "^0.4" }
pretty_env_logger = "^0.5"
thiserror = "1.0.57"
bitmask-enum = "^2.2"
parking_lot = "^0.12"
num_cpus = "^1.16"
boxcar = "^0.2.4"
dashmap = "5.5.3"
cooked-waker = "^5"
divan = "^0.1"
quiche = "^0.20"
bytes = "^1.5"
rand = { version = "^0.8", features = ["getrandom"] }
ring = "^0.17"


futures = { version = "^0.3", default-features = false }
futures-test = "0.3.30"
mio = { version = "^0.8.9", features = ["os-poll", "net"] }


rasi-syscall = { path = "./crates/syscall", default-features = false, version = "^0.1" }
rasi = { path = "./crates/rasi", version = "^0.1" }
rasi-ext = { path = "./crates/ext", default-features = false, version = "^0.1" }
rasi-spec = { path = "./crates/spec", version = "^0.1" }
rasi-default = { path = "./crates/default", version = "^0.1" }
