[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/RASI.git"
version = "0.1.1"

[workspace.dependencies]
log = { version = "^0.4" }
pretty_env_logger = "^0.5"
futures = { version = "^0.3", default-features = false }
bitmask-enum = "^2.2"

rasi-syscall = { path = "./crates/syscall", version = "^0.1" }
