[package]
description = "An implementation of http frameworks base on futures stream."
documentation = "https://docs.rs/futures-http"
edition.workspace = true
license = "MIT"
name = "futures-http"
repository.workspace = true
version.workspace = true
readme = "README.md"

[dependencies]
log = { workspace = true }
http = { workspace = true }
httparse = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
bytes = { workspace = true }
thiserror = { workspace = true }
rasi = { workspace = true, optional = true }
futures-boring = { workspace = true }

[dev-dependencies]
futures-test = { workspace = true }
rasi = { workspace = true }
rasi-mio = { workspace = true }
futures = { workspace = true, features = ["executor", "thread-pool"] }

[features]
default = ["json"]
json = ["serde", "serde_json"]
with_rasi = ["rasi"]
