[package]
description = "Rust Ethereum and other EVM-based chains client-side framework(Web3)"
documentation = "https://docs.rs/reweb3"
edition.workspace = true
license = "MIT"
name = "reweb3"
repository.workspace = true
version.workspace = true

[dependencies]
