[package]
description = "Futures-based jsonrpc v2.0 crate"
documentation = "https://docs.rs/futures-jsonrpcv2"
edition.workspace = true
license = "MIT"
name = "futures-jsonrpcv2"
repository.workspace = true
version.workspace = true
readme = "README.md"

[dependencies]
log = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures-waitmap = { workspace = true }
rasi = { workspace = true, optional = true }
futures-http = { workspace = true, optional = true }

[dev-dependencies]
futures-test = { workspace = true }
rasi = { workspace = true }
rasi-mio = { workspace = true }
futures = { workspace = true, features = ["executor", "thread-pool"] }

[features]
with_rasi = ["rasi", "futures-http/json", "futures-http/with_rasi"]
