[package]
description = "An implementation of Rust Asynchronous System Interface(RASI)"
documentation = "https://docs.rs/rasi"
edition.workspace = true
license = "MIT"
name = "rasi"
repository.workspace = true
version.workspace = true

[dependencies]
futures = { workspace = true }
rasi-syscall = { workspace = true }

[features]
default = ["net", "fs", "time", "executor"]

net = ["rasi-syscall/net"]
fs = ["rasi-syscall/fs"]
time = ["rasi-syscall/time"]
executor = ["rasi-syscall/executor"]
